<?php
/**
 * Edited by DEG
 */
?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 * @var $this DEG_SubcategoryView_Block_View
 */
?>
<?php
$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_imgHtml   = '';
if ($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="category-view" id="productGrid">
    <?php if($_imgUrl): ?>
        <?php echo $_imgHtml ?>
    <?php endif; ?>

    <?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
        <div class="category-description std">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </div>
    <?php endif; ?>

    <?php if($this->isContentMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>

    <?php elseif($this->isMixedMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
        <?php echo $this->getProductListHtml() ?>

    <?php elseif($this->isSubcategoryMixedMode()): ?>
        <?php echo $this->getCmsBlockHtml(); ?>
        <?php echo $this->getSubcategoryListHtml(); ?>

    <?php elseif($this->isSubcategoryMode()): ?>
        <?php echo $this->getSubcategoryListHtml(); ?>

    <?php else: ?>
        <?php echo $this->getProductListHtml() ?>
    <?php endif; ?>
</div>
